"""
Curated agricultural equipment catalog for Indian smallholder and commercial farms.

Each entry: name, use_case, price_range (display), price_min/max (for budget filter),
suitable_crops, category (icon grouping), optional links.
"""

from __future__ import annotations

# Realistic indicative price bands in INR (India, 2024–2026 retail / dealer range).
_EQUIPMENT_CATALOG: list[dict] = [
    {
        "id": 1,
        "name": "Power weeder / mini tiller (6–8 HP)",
        "use_case": "Inter-cultivation between crop rows, light puddling, and weed control on 0.5–2 ha plots.",
        "price_range": "₹72,000 – ₹1,45,000",
        "price_min": 72000,
        "price_max": 145000,
        "suitable_crops": ["Rice", "Maize", "Vegetables", "Groundnut"],
        "category": "tractor",
        "description": "Petrol or diesel; ideal where tractor access is limited. Reduces labour for weeding.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 2,
        "name": "Knapsack sprayer (16–20 L)",
        "use_case": "Foliar spraying of pesticides, fungicides, and liquid fertilisers on standing crops.",
        "price_range": "₹1,800 – ₹6,500",
        "price_min": 1800,
        "price_max": 6500,
        "suitable_crops": ["All crops"],
        "category": "sprayer",
        "description": "Brass/stainless lance variants last longer; choose battery models for large areas.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 3,
        "name": "Tractor-mounted boom sprayer",
        "use_case": "Uniform coverage across field crops; saves time vs manual knapsack on >2 ha.",
        "price_range": "₹38,000 – ₹95,000",
        "price_min": 38000,
        "price_max": 95000,
        "suitable_crops": ["Cotton", "Soybean", "Wheat", "Maize", "Sugarcane"],
        "category": "sprayer",
        "description": "Requires 35+ HP tractor; calibrate nozzle flow for chemical savings.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 4,
        "name": "Multi-crop seed-cum-fertiliser drill",
        "use_case": "Line sowing with basal fertiliser placement for cereals and oilseeds.",
        "price_range": "₹42,000 – ₹85,000",
        "price_min": 42000,
        "price_max": 85000,
        "suitable_crops": ["Wheat", "Rice (direct seeded)", "Gram", "Soybean", "Mustard"],
        "category": "seeder",
        "description": "Improves plant population and reduces seed rate vs broadcasting.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 5,
        "name": "Self-propelled combine harvester (compact)",
        "use_case": "Harvesting and threshing of paddy and wheat in one pass.",
        "price_range": "₹18,50,000 – ₹32,00,000",
        "price_min": 1850000,
        "price_max": 3200000,
        "suitable_crops": ["Rice", "Wheat", "Barley"],
        "category": "harvester",
        "description": "Custom hiring is common; ownership suits contractor groups or large farms.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 6,
        "name": "Submersible pump set (1–1.5 HP)",
        "use_case": "Lift irrigation from open wells or borewells up to ~40 m head.",
        "price_range": "₹9,500 – ₹22,000",
        "price_min": 9500,
        "price_max": 22000,
        "suitable_crops": ["All crops"],
        "category": "pump",
        "description": "Match HP to water column and discharge; use ISI-marked cable and starter.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 7,
        "name": "Drip irrigation kit (~1 acre)",
        "use_case": "Water-efficient fertigation for vegetables, fruit, and plantation crops.",
        "price_range": "₹28,000 – ₹55,000",
        "price_min": 28000,
        "price_max": 55000,
        "suitable_crops": ["Vegetables", "Tomato", "Coconut", "Coffee", "Pepper", "Arecanut"],
        "category": "pump",
        "description": "Subsidy often available via PMKSY; includes laterals, emitters, and filter.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 8,
        "name": "Rotavator (tractor PTO)",
        "use_case": "Fine seedbed preparation and residue incorporation before sowing.",
        "price_range": "₹58,000 – ₹1,25,000",
        "price_min": 58000,
        "price_max": 125000,
        "suitable_crops": ["Wheat", "Maize", "Vegetables", "Cotton", "Sugarcane"],
        "category": "plow",
        "description": "Width matched to tractor HP; popular in Rabi wheat belt.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 9,
        "name": "Rice transplanter (4-row walk-behind)",
        "use_case": "Machine transplanting of paddy seedlings for uniform spacing and labour saving.",
        "price_range": "₹2,20,000 – ₹3,80,000",
        "price_min": 220000,
        "price_max": 380000,
        "suitable_crops": ["Rice"],
        "category": "seeder",
        "description": "Requires mat nursery; subsidy schemes vary by state.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 10,
        "name": "Motorised winnower / grain cleaner",
        "use_case": "Separation of chaff and light impurities after threshing.",
        "price_range": "₹12,000 – ₹38,000",
        "price_min": 12000,
        "price_max": 38000,
        "suitable_crops": ["Rice", "Wheat", "Pulses", "Groundnut"],
        "category": "harvester",
        "description": "Improves mandi grade and reduces storage losses.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 11,
        "name": "Digital grain moisture meter",
        "use_case": "Check safe moisture before storage and sale to avoid mould and price penalty.",
        "price_range": "₹2,200 – ₹9,500",
        "price_min": 2200,
        "price_max": 9500,
        "suitable_crops": ["Rice", "Wheat", "Maize", "All crops"],
        "category": "tools",
        "description": "Handheld capacitive type; calibrate for your grain type if specified.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 12,
        "name": "Electric chaff cutter (2–3 HP)",
        "use_case": "Cutting green/dry fodder for cattle; improves digestibility.",
        "price_range": "₹22,000 – ₹48,000",
        "price_min": 22000,
        "price_max": 48000,
        "suitable_crops": ["Maize (fodder)", "Sorghum", "All crops"],
        "category": "tools",
        "description": "Pairs well with dairy; choose blade count per herd size.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 13,
        "name": "Coconut dehusking / processing unit (small)",
        "use_case": "Semi-mechanised dehusking for copra and tender coconut supply chains.",
        "price_range": "₹45,000 – ₹95,000",
        "price_min": 45000,
        "price_max": 95000,
        "suitable_crops": ["Coconut"],
        "category": "harvester",
        "description": "Throughput 100–300 nuts/hour depending on model; FPOs often invest jointly.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 14,
        "name": "Coffee pulper (hand-fed / small motor)",
        "use_case": "Wet processing of coffee cherry on estate or small grower lots.",
        "price_range": "₹35,000 – ₹88,000",
        "price_min": 35000,
        "price_max": 88000,
        "suitable_crops": ["Coffee"],
        "category": "harvester",
        "description": "Disc or drum type; maintain water flow to avoid bean damage.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 15,
        "name": "Arecanut/betel nut processing slicer (bench)",
        "use_case": "Sizing and slicing of arecanut for market grades (regional variants).",
        "price_range": "₹18,000 – ₹55,000",
        "price_min": 18000,
        "price_max": 55000,
        "suitable_crops": ["Arecanut"],
        "category": "tools",
        "description": "Safety guard mandatory; throughput depends on nut size and motor HP.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 16,
        "name": "Cono weeder (manual, set of 2)",
        "use_case": "Line weeding in flooded paddy without herbicide on narrow spacing.",
        "price_range": "₹700 – ₹1,400",
        "price_min": 700,
        "price_max": 1400,
        "suitable_crops": ["Rice"],
        "category": "plow",
        "description": "SRI and organic paddy systems; minimal cost, high labour saving per ha.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 17,
        "name": "Sugarcane sett cutting machine (motorised)",
        "use_case": "Uniform bud cutting for quick germination and reduced seed cane use.",
        "price_range": "₹28,000 – ₹62,000",
        "price_min": 28000,
        "price_max": 62000,
        "suitable_crops": ["Sugarcane"],
        "category": "seeder",
        "description": "Popular in UP and Maharashtra sugar belts; reduces sett-borne disease risk when paired with treatment.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 18,
        "name": "Cotton picking apron / spindle toolkit",
        "use_case": "Ergonomic hand picking and spindle maintenance for Bt cotton harvest.",
        "price_range": "₹350 – ₹2,500",
        "price_min": 350,
        "price_max": 2500,
        "suitable_crops": ["Cotton"],
        "category": "tools",
        "description": "Low-cost labour tools; combine with clean bags to preserve lint grade.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 19,
        "name": "Laser land leveler (tractor-drawn kit)",
        "use_case": "Precision levelling for water saving in paddy and wheat fields.",
        "price_range": "₹1,10,000 – ₹2,10,000",
        "price_min": 110000,
        "price_max": 210000,
        "suitable_crops": ["Rice", "Wheat", "Sugarcane"],
        "category": "plow",
        "description": "Often hired as service; subsidy under some state farm mechanisation schemes.",
        "youtube_link": "",
        "purchase_link": "",
    },
    {
        "id": 20,
        "name": "Mist blower (orchard sprayer)",
        "use_case": "Tall crops: mango, coconut, coffee — penetrates canopy for pest control.",
        "price_range": "₹22,000 – ₹48,000",
        "price_min": 22000,
        "price_max": 48000,
        "suitable_crops": ["Mango", "Coconut", "Coffee", "Pepper", "Arecanut"],
        "category": "sprayer",
        "description": "Two-stroke or four-stroke backpack; wear PPE and spray in calm hours.",
        "youtube_link": "",
        "purchase_link": "",
    },
]


def get_equipment_catalog() -> list[dict]:
    """Return a shallow copy of the full catalog (safe to mutate in routes)."""
    return [dict(item) for item in _EQUIPMENT_CATALOG]


def list_suitable_crop_labels() -> list[str]:
    """Unique crop labels for filter dropdowns, sorted with 'All crops' first."""
    seen: set[str] = set()
    for item in _EQUIPMENT_CATALOG:
        for c in item.get("suitable_crops") or []:
            seen.add(str(c).strip())
    # Prefer logical order: All crops first, then alphabetical
    rest = sorted(c for c in seen if c.lower() != "all crops")
    out = []
    if any(c.lower() == "all crops" for c in seen):
        out.append("All crops")
    out.extend(rest)
    return out
